name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Archive JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Deploy to EC2 (placeholder)
        run: |
          echo "Deploying to EC2 instance..."
          # TODO: Add SSH/scp/rsync commands to deploy to your EC2 instance
          # Example:
          # scp -i ${{ secrets.EC2_SSH_KEY }} target/*.jar ec2-user@<EC2_PUBLIC_IP>:/home/ec2-user/
